//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef5uc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        public int ChecksID { get; set; }
        public Nullable<int> TovatiID { get; set; }
        public Nullable<int> ChecksInfoID { get; set; }
    
        public virtual ChecksInfo ChecksInfo { get; set; }
        public virtual Tovari Tovari { get; set; }
    }
}
