//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef5uc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korzina()
        {
            this.Tovari = new HashSet<Tovari>();
        }
    
        public int KorzinaID { get; set; }
        public Nullable<int> OrdersID { get; set; }
        public Nullable<int> Kollichestvo { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<int> SotrudnikiID { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tovari> Tovari { get; set; }
    }
}
