//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef5uc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalavaClub1Entities : DbContext
    {
        public SalavaClub1Entities()
            : base("name=SalavaClub1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checks> Checks { get; set; }
        public virtual DbSet<ChecksInfo> ChecksInfo { get; set; }
        public virtual DbSet<KAtegoriaTovara> KAtegoriaTovara { get; set; }
        public virtual DbSet<Korzina> Korzina { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Pokupatel> Pokupatel { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Tovari> Tovari { get; set; }
        public virtual DbSet<VozvratTovara> VozvratTovara { get; set; }
    }
}
