//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef5uc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tovari()
        {
            this.Checks = new HashSet<Checks>();
        }
    
        public int TOvariID { get; set; }
        public string NameTovara { get; set; }
        public Nullable<decimal> PriceUnit { get; set; }
        public Nullable<int> inStock { get; set; }
        public Nullable<int> KAtegoriaTovaraID { get; set; }
        public Nullable<int> KorzinaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual KAtegoriaTovara KAtegoriaTovara { get; set; }
        public virtual Korzina Korzina { get; set; }
    }
}
